-- ============================================
-- Migration 003: Flatten orders table for WhatsApp/n8n integration
-- Run this in Supabase SQL Editor
-- ============================================

-- 1. Add flat customer & order-detail columns (the app & webhook use these directly)
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS customer_name  TEXT,
  ADD COLUMN IF NOT EXISTS customer_phone TEXT,
  ADD COLUMN IF NOT EXISTS items          JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS delivery_time  TIMESTAMPTZ;

-- 2. Drop the FK constraint so business_id can be NULL for WhatsApp orders
--    (WhatsApp orders come in without a registered business UUID)
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_business_id_fkey;

-- 3. Make business_id nullable
ALTER TABLE orders ALTER COLUMN business_id DROP NOT NULL;

-- 4. Make order_number nullable (generated by the app; WhatsApp orders don't have one)
ALTER TABLE orders ALTER COLUMN order_number DROP NOT NULL;

-- 5. Give total_amount a safe default so inserts without it don't fail
ALTER TABLE orders ALTER COLUMN total_amount SET DEFAULT 0;
ALTER TABLE orders ALTER COLUMN total_amount DROP NOT NULL;
